import { createHash, randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { invariant } from "../core/errors.js";
import { ROLES } from "../core/metadata.js";
import { safeManifestPath } from "../core/security.js";
import { ensureRuntimeLayout, runtimeArea } from "../core/paths.js";
import { stableStringify } from "../core/util.js";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const PACKAGE_VERSION = JSON.parse(readFileSync(path.join(packageRoot, "package.json"), "utf8")).version;
const INSTALL_MANIFEST_VERSION = 4;

const DEFAULT_CODEX_PROJECT_CONFIG = `# Generated by Metis. Existing project configuration is never replaced.
[features]
goals = true

[features.multi_agent_v2]
enabled = true
max_concurrent_threads_per_session = 8
hide_spawn_agent_metadata = false
tool_namespace = "agents"
expose_spawn_agent_model_overrides = true
wait_agent_enabled = true
`;

const AGENT_ROLE_NAMES = [...ROLES];
const CLAUDE_AGENT_FILES = AGENT_ROLE_NAMES.map((name) => `${name}.md`);
const OPENCODE_AGENT_FILES = AGENT_ROLE_NAMES.map((name) => `metis-${name}.md`);

function sha256Buffer(value) {
  return createHash("sha256").update(value).digest("hex");
}

function assertGitProjectRoot(projectRoot) {
  try {
    execFileSync("git", ["rev-parse", "--show-toplevel"], {
      cwd: projectRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"]
    });
  } catch {
    invariant(false, "GIT_REQUIRED", "Metis host attachment requires a Git project root.");
  }
}

function fileHash(file) {
  return sha256Buffer(readFileSync(file));
}

function manifestPath(projectRoot) {
  return safeManifestPath(projectRoot, ".agents/metis/install-manifest.json", { code: "INSTALL_MANIFEST_PATH_INVALID" }).absolute;
}

function relativeToProject(projectRoot, target) {
  return path.relative(projectRoot, target).replaceAll(path.sep, "/");
}

function managedPath(projectRoot, relative, code = "MANIFEST_PATH_INVALID") {
  return safeManifestPath(projectRoot, relative, { code });
}

function validateManifest(projectRoot, manifest) {
  invariant(manifest && typeof manifest === "object" && !Array.isArray(manifest), "INSTALL_MANIFEST_INVALID", "The install manifest must be an object.");
  invariant(Array.isArray(manifest.hosts), "INSTALL_MANIFEST_INVALID", "The install manifest hosts must be an array.");
  invariant(Array.isArray(manifest.files), "INSTALL_MANIFEST_INVALID", "The install manifest files must be an array.");
  for (const record of manifest.files) {
    invariant(record && typeof record === "object", "INSTALL_MANIFEST_INVALID", "Each install manifest file record must be an object.");
    managedPath(projectRoot, record.path);
    if (record.backupPath) managedPath(projectRoot, record.backupPath);
    for (const backupPath of record.recoveryBackups ?? []) managedPath(projectRoot, backupPath);
  }
  if (manifest.marketplace?.path) managedPath(projectRoot, manifest.marketplace.path);
  if (manifest.ignore?.file) managedPath(projectRoot, manifest.ignore.file);
  return manifest;
}

function readManifest(projectRoot) {
  const file = manifestPath(projectRoot);
  if (!existsSync(file)) return null;
  const manifest = JSON.parse(readFileSync(file, "utf8"));
  invariant(
    manifest.version === INSTALL_MANIFEST_VERSION,
    "INSTALL_MANIFEST_VERSION",
    "This installation was created by an incompatible Metis version. Remove it before installing this release."
  );
  return validateManifest(projectRoot, manifest);
}

function newManifest(existing = null) {
  return existing ?? {
    version: INSTALL_MANIFEST_VERSION,
    installationId: randomUUID(),
    hosts: [],
    files: [],
    marketplace: null,
    ignore: { file: null, entries: [] },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
}

function writeManifest(projectRoot, manifest) {
  validateManifest(projectRoot, manifest);
  manifest.updatedAt = new Date().toISOString();
  const file = manifestPath(projectRoot);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, `${stableStringify(manifest)}\n`, "utf8");
  return relativeToProject(projectRoot, file);
}

function recordFor(manifest, relative) {
  return manifest.files.find((item) => item.path === relative) ?? null;
}

function backupExisting(projectRoot, target, relative, manifest, label = "original") {
  const safeRelative = managedPath(projectRoot, relative, "INSTALL_PATH_INVALID").relative;
  const backupRelative = `.metis/backups/install/${manifest.installationId}/${label}/${safeRelative}`;
  const backup = managedPath(projectRoot, backupRelative, "INSTALL_BACKUP_PATH_INVALID").absolute;
  mkdirSync(path.dirname(backup), { recursive: true });
  copyFileSync(target, backup);
  return backupRelative;
}

function setManagedFile(projectRoot, relative, content, hosts, options, manifest) {
  const safeTarget = managedPath(projectRoot, relative, "INSTALL_PATH_INVALID");
  relative = safeTarget.relative;
  const target = safeTarget.absolute;
  const expected = Buffer.isBuffer(content) ? content : Buffer.from(String(content), "utf8");
  const installedSha256 = sha256Buffer(expected);
  const existingRecord = recordFor(manifest, relative);
  const currentExists = existsSync(target);
  if (currentExists && !lstatSync(target).isFile()) {
    return { path: relative, status: "conflict", reason: "target is not a regular file" };
  }
  const currentHash = currentExists ? fileHash(target) : null;
  const sourceEqualsTarget = options.sourcePath && path.resolve(options.sourcePath) === path.resolve(target);
  if (sourceEqualsTarget) {
    const record = existingRecord ?? {
      path: relative,
      hosts: [],
      installedSha256: currentHash,
      managed: true,
      created: false,
      backupPath: null,
      recoveryBackups: [],
      mode: options.mode ?? null
    };
    record.hosts = [...new Set([...record.hosts, ...hosts])].sort();
    record.installedSha256 = currentHash;
    if (!existingRecord) manifest.files.push(record);
    return { path: relative, status: "current", sha256: currentHash };
  }
  if (currentExists && currentHash === installedSha256) {
    const record = existingRecord ?? {
      path: relative,
      hosts: [],
      installedSha256,
      managed: false,
      created: false,
      backupPath: null,
      recoveryBackups: [],
      mode: options.mode ?? null
    };
    record.hosts = [...new Set([...record.hosts, ...hosts])].sort();
    record.installedSha256 = installedSha256;
    if (!existingRecord) manifest.files.push(record);
    return { path: relative, status: existingRecord ? "current" : "adopted", sha256: installedSha256 };
  }
  const safelyOwned = Boolean(existingRecord?.managed && currentHash === existingRecord.installedSha256);
  if (currentExists && !safelyOwned && !options.force) {
    return { path: relative, status: "preserved", reason: "existing file differs; use --force to replace it" };
  }
  let record = existingRecord;
  if (!record) {
    record = {
      path: relative,
      hosts: [],
      installedSha256: null,
      managed: true,
      created: !currentExists,
      backupPath: null,
      recoveryBackups: [],
      mode: options.mode ?? null
    };
    manifest.files.push(record);
  }
  if (currentExists && !safelyOwned) {
    if (!record.backupPath) record.backupPath = backupExisting(projectRoot, target, relative, manifest, "original");
    else record.recoveryBackups.push(backupExisting(projectRoot, target, relative, manifest, `modified-${Date.now()}`));
  }
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, expected, options.mode ? { mode: options.mode } : undefined);
  record.hosts = [...new Set([...record.hosts, ...hosts])].sort();
  record.installedSha256 = installedSha256;
  record.managed = true;
  record.mode = options.mode ?? record.mode ?? null;
  return { path: relative, status: currentExists ? "updated" : "created", sha256: installedSha256 };
}

function copyManagedFile(projectRoot, source, relative, hosts, options, manifest) {
  return setManagedFile(projectRoot, relative, readFileSync(source), hosts, { ...options, sourcePath: source }, manifest);
}

function walkFiles(root, relative = "") {
  const output = [];
  if (!existsSync(root)) return output;
  for (const entry of readdirSync(path.join(root, relative), { withFileTypes: true })) {
    const child = path.join(relative, entry.name);
    if (entry.isDirectory()) output.push(...walkFiles(root, child));
    else if (entry.isFile()) output.push(child);
  }
  return output.sort();
}

function copyTree(projectRoot, sourceRoot, targetRelative, hosts, options, manifest) {
  return walkFiles(sourceRoot).map((relative) => copyManagedFile(
    projectRoot,
    path.join(sourceRoot, relative),
    path.posix.join(targetRelative, relative.replaceAll(path.sep, "/")),
    hosts,
    options,
    manifest
  ));
}

function installedSkillText(projectRoot, skillName = "metis") {
  const source = readFileSync(path.join(packageRoot, "skills", skillName, "SKILL.md"), "utf8");
  const launcher = path.join(projectRoot, ".agents", "metis", "metis.mjs").replaceAll("\\", "/");
  return source
    .replace("node --no-warnings <skill-directory>/scripts/metis.mjs", `node --no-warnings "${launcher}"`)
    .replace("node --no-warnings <skill-directory>/../metis/scripts/metis.mjs", `node --no-warnings "${launcher}"`);
}

function installSkill(projectRoot, targetRelative, hosts, options, manifest, skillName = "metis") {
  const results = [setManagedFile(projectRoot, path.posix.join(targetRelative, "SKILL.md"), installedSkillText(projectRoot, skillName), hosts, options, manifest)];
  for (const directory of ["references", "agents", "capabilities"]) {
    results.push(...copyTree(projectRoot, path.join(packageRoot, "skills", skillName, directory), path.posix.join(targetRelative, directory), hosts, options, manifest));
  }
  return results;
}

function installRuntime(projectRoot, options, manifest) {
  const target = ".agents/metis/runtime";
  const results = [];
  for (const directory of ["src", "skills", "commands", "agents", "adapters", ".codex-plugin", ".claude-plugin"]) {
    results.push(...copyTree(projectRoot, path.join(packageRoot, directory), path.posix.join(target, directory), ["common"], options, manifest));
  }
  const browserVerifier = path.join(packageRoot, "scripts", "chromium-browser-verifier.mjs");
  results.push(copyManagedFile(
    projectRoot,
    browserVerifier,
    path.posix.join(target, "scripts", "chromium-browser-verifier.mjs"),
    ["common"],
    { ...options, mode: 0o755 },
    manifest
  ));
  for (const file of ["LICENSE", "plugin.json"]) {
    const source = path.join(packageRoot, file);
    if (existsSync(source)) results.push(copyManagedFile(projectRoot, source, path.posix.join(target, file), ["common"], options, manifest));
  }
  results.push(setManagedFile(projectRoot, path.posix.join(target, "package.json"), `${JSON.stringify({
    name: "metis-runtime",
    version: PACKAGE_VERSION,
    private: true,
    type: "module",
    engines: { node: ">=22.16.0" }
  }, null, 2)}\n`, ["common"], options, manifest));
  const launcher = `#!/usr/bin/env -S node --no-warnings\nimport { main } from "./runtime/src/cli.js";\nprocess.exitCode = await main();\n`;
  results.push(setManagedFile(projectRoot, ".agents/metis/metis.mjs", launcher, ["common"], { ...options, mode: 0o755 }, manifest));
  return { target, launcher: ".agents/metis/metis.mjs", results };
}

function marketplaceEntry() {
  return {
    name: "metis",
    source: { source: "local", path: "./plugins/metis" },
    policy: { installation: "AVAILABLE", authentication: "ON_INSTALL" },
    category: "Developer Tools"
  };
}

function updateMarketplace(projectRoot, options, manifest) {
  const relative = ".agents/plugins/marketplace.json";
  const file = managedPath(projectRoot, relative, "INSTALL_MARKETPLACE_PATH_INVALID").absolute;
  let marketplace = {
    name: "metis-workspace",
    interface: { displayName: "Metis Workspace Plugins" },
    plugins: []
  };
  const fileExisted = existsSync(file);
  if (fileExisted) {
    try { marketplace = JSON.parse(readFileSync(file, "utf8")); }
    catch (error) { throw new Error(`Cannot update invalid marketplace file ${relative}: ${error.message}`); }
  }
  marketplace.plugins = Array.isArray(marketplace.plugins) ? marketplace.plugins : [];
  const installedEntry = marketplaceEntry();
  const index = marketplace.plugins.findIndex((item) => item?.name === "metis");
  const currentEntry = index >= 0 ? marketplace.plugins[index] : null;
  if (currentEntry && stableStringify(currentEntry) !== stableStringify(installedEntry) && !options.force) {
    return { path: relative, status: "preserved", reason: "existing marketplace entry differs; use --force" };
  }
  if (!manifest.marketplace) {
    manifest.marketplace = {
      path: relative,
      fileCreated: !fileExisted,
      previousEntry: currentEntry,
      installedEntry
    };
  }
  if (index >= 0) marketplace.plugins[index] = installedEntry;
  else marketplace.plugins.push(installedEntry);
  if (fileExisted && stableStringify(JSON.parse(readFileSync(file, "utf8"))) === stableStringify(marketplace)) {
    return { path: relative, status: "current" };
  }
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, `${stableStringify(marketplace)}\n`, "utf8");
  return { path: relative, status: index >= 0 ? "updated" : "created" };
}

function installCodex(projectRoot, options, manifest) {
  const results = [];
  results.push(copyManagedFile(projectRoot, path.join(packageRoot, "commands", "metis.md"), "plugins/metis/commands/metis.md", ["codex"], options, manifest));
  results.push(...installSkill(projectRoot, ".agents/skills/metis", ["codex"], options, manifest));
  results.push(...installSkill(projectRoot, ".agents/skills/metis-model", ["codex"], options, manifest, "model"));
  for (const directory of [".codex-plugin", "agents"]) {
    results.push(...copyTree(projectRoot, path.join(packageRoot, directory), path.posix.join("plugins/metis", directory), ["codex"], options, manifest));
  }
  results.push(...installSkill(projectRoot, "plugins/metis/skills/metis", ["codex"], options, manifest));
  results.push(...installSkill(projectRoot, "plugins/metis/skills/model", ["codex"], options, manifest, "model"));
  for (const file of ["LICENSE", "plugin.json"]) {
    const source = path.join(packageRoot, file);
    if (existsSync(source)) results.push(copyManagedFile(projectRoot, source, path.posix.join("plugins/metis", file), ["codex"], options, manifest));
  }
  for (const file of readdirSync(path.join(packageRoot, "agents")).filter((name) => name.endsWith(".toml"))) {
    results.push(copyManagedFile(projectRoot, path.join(packageRoot, "agents", file), path.posix.join(".codex/agents", file), ["codex"], options, manifest));
  }
  const configRelative = ".codex/config.toml";
  if (!existsSync(path.join(projectRoot, configRelative))) {
    results.push(setManagedFile(projectRoot, configRelative, DEFAULT_CODEX_PROJECT_CONFIG, ["codex"], options, manifest));
  } else {
    results.push({ path: configRelative, status: "preserved", reason: "existing Codex project config" });
  }
  return { results, marketplace: updateMarketplace(projectRoot, options, manifest) };
}

function installClaude(projectRoot, options, manifest) {
  const source = path.join(packageRoot, "adapters", "claude");
  const results = [];
  results.push(copyManagedFile(projectRoot, path.join(source, "commands", "metis.md"), ".claude/commands/metis.md", ["claude"], options, manifest));
  results.push(...installSkill(projectRoot, ".claude/skills/metis", ["claude"], options, manifest));
  results.push(...installSkill(projectRoot, ".claude/skills/metis-model", ["claude"], options, manifest, "model"));
  for (const file of CLAUDE_AGENT_FILES) {
    results.push(copyManagedFile(projectRoot, path.join(source, "agents", file), `.claude/agents/metis-${file}`, ["claude"], options, manifest));
  }
  return { results };
}

function installOpenCode(projectRoot, options, manifest) {
  const source = path.join(packageRoot, "adapters", "opencode", ".opencode");
  const results = [];
  results.push(copyManagedFile(projectRoot, path.join(source, "commands", "metis.md"), ".opencode/commands/metis.md", ["opencode"], options, manifest));
  results.push(...installSkill(projectRoot, ".opencode/skills/metis", ["opencode"], options, manifest));
  results.push(...installSkill(projectRoot, ".opencode/skills/metis-model", ["opencode"], options, manifest, "model"));
  for (const file of OPENCODE_AGENT_FILES) {
    results.push(copyManagedFile(projectRoot, path.join(source, "agents", file), `.opencode/agents/${file}`, ["opencode"], options, manifest));
  }
  return { results };
}

function localIgnoreFile(projectRoot) {
  const gitDirectory = path.join(projectRoot, ".git");
  if (existsSync(gitDirectory) && lstatSync(gitDirectory).isDirectory()) {
    return managedPath(projectRoot, ".git/info/exclude", "INSTALL_IGNORE_PATH_INVALID").absolute;
  }
  return managedPath(projectRoot, ".gitignore", "INSTALL_IGNORE_PATH_INVALID").absolute;
}

function ignoreEntries(selected) {
  const entries = [
    { line: "/.metis/", hosts: ["common"] },
    { line: "/.agents/metis/", hosts: ["common"] }
  ];
  if (selected.includes("codex")) entries.push(
    { line: "/.agents/skills/metis/", hosts: ["codex"] },
    { line: "/.agents/plugins/marketplace.json", hosts: ["codex"] },
    { line: "/plugins/metis/", hosts: ["codex"] },
    { line: "/.codex/config.toml", hosts: ["codex"] },
    { line: "/.codex/agents/metis-*.toml", hosts: ["codex"] }
  );
  if (selected.includes("claude")) entries.push(
    { line: "/.claude/commands/metis.md", hosts: ["claude"] },
    { line: "/.claude/skills/metis/", hosts: ["claude"] },
    { line: "/.claude/agents/metis-*.md", hosts: ["claude"] }
  );
  if (selected.includes("opencode")) entries.push(
    { line: "/.opencode/commands/metis.md", hosts: ["opencode"] },
    { line: "/.opencode/skills/metis/", hosts: ["opencode"] },
    { line: "/.opencode/agents/metis-*.md", hosts: ["opencode"] }
  );
  return entries;
}

function ensureIgnoreEntries(projectRoot, selected, manifest) {
  const file = localIgnoreFile(projectRoot);
  mkdirSync(path.dirname(file), { recursive: true });
  const original = existsSync(file) ? readFileSync(file, "utf8") : "";
  const lines = new Set(original.split(/\r?\n/u));
  const additions = [];
  for (const entry of ignoreEntries(selected)) {
    const existing = manifest.ignore.entries.find((item) => item.line === entry.line);
    if (existing) existing.hosts = [...new Set([...existing.hosts, ...entry.hosts])].sort();
    else manifest.ignore.entries.push({ ...entry, added: !lines.has(entry.line) });
    if (!lines.has(entry.line)) {
      additions.push(entry.line);
      lines.add(entry.line);
    }
  }
  if (additions.length > 0) {
    const prefix = original && !original.endsWith("\n") ? "\n" : "";
    writeFileSync(file, `${original}${prefix}${additions.join("\n")}\n`, "utf8");
  }
  manifest.ignore.file = relativeToProject(projectRoot, file);
  return { file: manifest.ignore.file, added: additions };
}

function removeExactLines(file, lines, dryRun) {
  if (!existsSync(file) || lines.length === 0) return [];
  const remove = new Set(lines);
  const original = readFileSync(file, "utf8");
  const removed = original.split(/\r?\n/u).filter((line) => remove.has(line));
  if (dryRun || removed.length === 0) return removed;
  let next = original.split(/\r?\n/u).filter((line) => !remove.has(line)).join("\n").replace(/\n{3,}/gu, "\n\n");
  if (next && !next.endsWith("\n")) next += "\n";
  if (!next.trim()) rmSync(file, { force: true });
  else writeFileSync(file, next, "utf8");
  return removed;
}

function pruneEmptyParents(projectRoot, target) {
  let current = path.dirname(target);
  const root = path.resolve(projectRoot);
  while (path.resolve(current).startsWith(`${root}${path.sep}`)) {
    try {
      if (readdirSync(current).length > 0) break;
      rmSync(current, { recursive: true, force: true });
    } catch { break; }
    current = path.dirname(current);
  }
}

export function installAdapters(projectRoot, hosts, force = false) {
  assertGitProjectRoot(projectRoot);
  ensureRuntimeLayout(projectRoot);
  const selected = hosts.includes("all") ? ["codex", "claude", "opencode"] : [...new Set(hosts)];
  invariant(selected.length > 0, "HOST_REQUIRED", "Select at least one host.");
  for (const host of selected) invariant(["codex", "claude", "opencode"].includes(host), "HOST_INVALID", `Unsupported host: ${host}.`);
  const existingManifest = readManifest(projectRoot);
  const manifest = newManifest(existingManifest);
  const previousManifestState = existingManifest ? stableStringify({ ...existingManifest, updatedAt: undefined }) : null;
  const options = { force: Boolean(force) };
  const runtime = installRuntime(projectRoot, options, manifest);
  const installed = {};
  if (selected.includes("codex")) installed.codex = installCodex(projectRoot, options, manifest);
  if (selected.includes("claude")) installed.claude = installClaude(projectRoot, options, manifest);
  if (selected.includes("opencode")) installed.opencode = installOpenCode(projectRoot, options, manifest);
  manifest.hosts = [...new Set([...manifest.hosts, ...selected])].sort();
  const ignore = ensureIgnoreEntries(projectRoot, selected, manifest);
  const results = [
    ...runtime.results,
    ...Object.values(installed).flatMap((value) => value.results ?? [])
  ];
  const manifestStateChanged = !existingManifest
    || previousManifestState !== stableStringify({ ...manifest, updatedAt: undefined })
    || results.some((item) => ["created", "updated"].includes(item.status))
    || ignore.added.length > 0
    || Object.values(installed).some((value) => ["created", "updated"].includes(value.marketplace?.status));
  const manifestFile = manifestStateChanged
    ? writeManifest(projectRoot, manifest)
    : relativeToProject(projectRoot, manifestPath(projectRoot));
  return {
    runtime: {
      target: path.join(projectRoot, runtime.target),
      targetRelative: runtime.target,
      launcher: path.join(projectRoot, runtime.launcher),
      launcherRelative: runtime.launcher
    },
    installed,
    ignore,
    stateIgnore: managedPath(projectRoot, ignore.file, "INSTALL_IGNORE_PATH_INVALID").absolute,
    manifest: manifestFile,
    created: results.filter((item) => item.status === "created").map((item) => item.path),
    updated: results.filter((item) => item.status === "updated").map((item) => item.path),
    preserved: results.filter((item) => item.status === "preserved"),
    conflicts: results.filter((item) => item.status === "conflict")
  };
}

function sameJson(a, b) {
  return stableStringify(a) === stableStringify(b);
}

function uninstallMarketplace(projectRoot, manifest, options) {
  if (!manifest.marketplace) return { status: "absent" };
  const file = managedPath(projectRoot, manifest.marketplace.path, "INSTALL_MARKETPLACE_PATH_INVALID").absolute;
  if (!existsSync(file)) return { status: "missing" };
  let marketplace;
  try { marketplace = JSON.parse(readFileSync(file, "utf8")); }
  catch { return { status: "conflict", reason: "marketplace file is invalid JSON" }; }
  marketplace.plugins = Array.isArray(marketplace.plugins) ? marketplace.plugins : [];
  const index = marketplace.plugins.findIndex((item) => item?.name === "metis");
  const current = index >= 0 ? marketplace.plugins[index] : null;
  if (current && !sameJson(current, manifest.marketplace.installedEntry) && !options.forceModified) {
    return { status: "conflict", reason: "marketplace entry changed after installation" };
  }
  if (options.dryRun) return { status: "would-remove" };
  if (index >= 0) {
    if (manifest.marketplace.previousEntry) marketplace.plugins[index] = manifest.marketplace.previousEntry;
    else marketplace.plugins.splice(index, 1);
  }
  if (manifest.marketplace.fileCreated && marketplace.plugins.length === 0) {
    rmSync(file, { force: true });
    pruneEmptyParents(projectRoot, file);
  } else {
    writeFileSync(file, `${stableStringify(marketplace)}\n`, "utf8");
  }
  return { status: "removed" };
}

function uninstallBackupPath(projectRoot, options, relative) {
  const id = String(options.uninstallId ?? `uninstall-${Date.now()}`).replace(/[^A-Za-z0-9._-]/gu, "-");
  const safeRelative = managedPath(projectRoot, relative, "INSTALL_PATH_INVALID").relative;
  const backupRelative = `.metis/backups/uninstall/${id}/${safeRelative}`;
  const backup = managedPath(projectRoot, backupRelative, "INSTALL_BACKUP_PATH_INVALID");
  invariant(backup.absolute.startsWith(`${runtimeArea(projectRoot, "backups")}${path.sep}`), "INSTALL_BACKUP_PATH_INVALID", "The uninstall backup path must remain inside the backup area.");
  return { relative: backup.relative, absolute: backup.absolute };
}

function restoreOrRemoveFile(projectRoot, record, options) {
  const safeTarget = managedPath(projectRoot, record.path, "INSTALL_MANIFEST_PATH_INVALID");
  record.path = safeTarget.relative;
  const target = safeTarget.absolute;
  const exists = existsSync(target);
  if (exists && !lstatSync(target).isFile()) {
    return { path: record.path, status: "conflict", reason: "managed path is not a regular file" };
  }
  const currentHash = exists ? fileHash(target) : null;
  const modified = exists && currentHash !== record.installedSha256;
  let modifiedBackup = null;
  if (modified && !options.forceModified) {
    return { path: record.path, status: "conflict", reason: "file changed after installation", currentSha256: currentHash, installedSha256: record.installedSha256 };
  }
  if (modified && options.forceModified && options.backupModified) {
    modifiedBackup = uninstallBackupPath(projectRoot, options, record.path);
  }
  const action = record.backupPath ? "restore" : record.managed ? "remove" : "preserve";
  if (options.dryRun) {
    return {
      path: record.path,
      status: modifiedBackup ? `would-backup-and-${action}` : `would-${action}`,
      modified,
      ...(modifiedBackup ? { backupPath: modifiedBackup.relative } : {})
    };
  }
  if (modifiedBackup) {
    mkdirSync(path.dirname(modifiedBackup.absolute), { recursive: true });
    copyFileSync(target, modifiedBackup.absolute);
  }
  const safeBackup = record.backupPath ? managedPath(projectRoot, record.backupPath, "INSTALL_MANIFEST_PATH_INVALID") : null;
  if (safeBackup && existsSync(safeBackup.absolute)) {
    mkdirSync(path.dirname(target), { recursive: true });
    copyFileSync(safeBackup.absolute, target);
    return { path: record.path, status: modifiedBackup ? "restored-with-backup" : "restored", modified, ...(modifiedBackup ? { backupPath: modifiedBackup.relative } : {}) };
  }
  if (record.managed && exists) {
    rmSync(target, { force: true });
    pruneEmptyParents(projectRoot, target);
    return { path: record.path, status: modifiedBackup ? "removed-with-backup" : "removed", modified, ...(modifiedBackup ? { backupPath: modifiedBackup.relative } : {}) };
  }
  return { path: record.path, status: record.managed ? "missing" : "preserved", modified, ...(modifiedBackup ? { backupPath: modifiedBackup.relative } : {}) };
}

export function uninstallAdapters(projectRoot, hosts = ["all"], options = {}) {
  const forceModified = Boolean(options.forceModified);
  const effectiveOptions = {
    dryRun: Boolean(options.dryRun),
    forceModified,
    backupModified: forceModified && options.backupModified !== false,
    uninstallId: options.uninstallId ?? `uninstall-${Date.now()}`,
    preflight: options.preflight !== false
  };
  const manifest = readManifest(projectRoot);
  invariant(manifest, "INSTALL_MANIFEST_MISSING", "Metis install manifest is missing. Refusing to guess which files are safe to remove.");
  if (!effectiveOptions.dryRun && effectiveOptions.preflight) {
    const preview = uninstallAdapters(projectRoot, hosts, {
      ...effectiveOptions,
      dryRun: true,
      preflight: false
    });
    if (preview.conflicts.length > 0) return { ...preview, dryRun: false, applied: false, preflight: true };
  }
  options = effectiveOptions;
  if (options.backupModified && !options.dryRun) ensureRuntimeLayout(projectRoot);
  const requested = hosts.includes("all") ? [...manifest.hosts] : [...new Set(hosts)];
  for (const host of requested) invariant(["codex", "claude", "opencode"].includes(host), "HOST_INVALID", `Unsupported host: ${host}.`);
  const desiredRemaining = manifest.hosts.filter((host) => !requested.includes(host));
  const removeCommon = desiredRemaining.length === 0;
  const fileResults = [];
  const retainedRecords = [];
  const failedHosts = new Set();
  for (const record of manifest.files) {
    const targetedHosts = record.hosts.filter((host) => requested.includes(host) || (host === "common" && removeCommon));
    if (targetedHosts.length === 0) {
      retainedRecords.push(record);
      continue;
    }
    const remainingRecordHosts = record.hosts.filter((host) => !targetedHosts.includes(host));
    if (remainingRecordHosts.length > 0) {
      retainedRecords.push({ ...record, hosts: remainingRecordHosts });
      continue;
    }
    const result = restoreOrRemoveFile(projectRoot, record, options);
    fileResults.push(result);
    if (result.status === "conflict") {
      retainedRecords.push(record);
      for (const host of targetedHosts.filter((host) => host !== "common")) failedHosts.add(host);
    }
  }
  let marketplace = { status: "not-requested" };
  if (requested.includes("codex")) {
    marketplace = uninstallMarketplace(projectRoot, manifest, options);
    if (marketplace.status === "conflict") failedHosts.add("codex");
  }
  const successfulHosts = requested.filter((host) => !failedHosts.has(host));
  const effectiveRemaining = [...new Set([
    ...desiredRemaining,
    ...failedHosts
  ])].sort();
  const ignoreToRemove = [];
  for (const entry of manifest.ignore.entries ?? []) {
    const nextHosts = entry.hosts.filter((host) => !successfulHosts.includes(host) && !(host === "common" && effectiveRemaining.length === 0));
    if (nextHosts.length === 0 && entry.added) ignoreToRemove.push(entry.line);
    else entry.hosts = nextHosts;
  }
  manifest.ignore.entries = (manifest.ignore.entries ?? []).filter((entry) => entry.hosts.length > 0);
  const ignoreFile = manifest.ignore.file ? managedPath(projectRoot, manifest.ignore.file, "INSTALL_IGNORE_PATH_INVALID").absolute : localIgnoreFile(projectRoot);
  const ignoreRemoved = removeExactLines(ignoreFile, ignoreToRemove, Boolean(options.dryRun));
  if (!options.dryRun) {
    manifest.files = retainedRecords;
    manifest.hosts = effectiveRemaining;
    if (!effectiveRemaining.includes("codex") && marketplace.status !== "conflict") manifest.marketplace = null;
    if (manifest.hosts.length > 0 || failedHosts.size > 0) writeManifest(projectRoot, manifest);
    else {
      rmSync(manifestPath(projectRoot), { force: true });
      pruneEmptyParents(projectRoot, manifestPath(projectRoot));
    }
  }
  const conflicts = [
    ...fileResults.filter((item) => item.status === "conflict"),
    ...(marketplace.status === "conflict" ? [{ path: manifest.marketplace?.path ?? ".agents/plugins/marketplace.json", ...marketplace }] : [])
  ];
  return {
    requested,
    removedHosts: successfulHosts,
    remainingHosts: effectiveRemaining,
    dryRun: Boolean(options.dryRun),
    applied: !options.dryRun,
    forceModified: Boolean(options.forceModified),
    backupModified: Boolean(options.backupModified),
    uninstallId: options.uninstallId,
    files: fileResults,
    backups: fileResults.filter((item) => item.backupPath).map((item) => ({ path: item.path, backupPath: item.backupPath })),
    conflicts,
    marketplace,
    ignoreRemoved,
    statePreserved: existsSync(path.join(projectRoot, ".metis"))
  };
}

export function installationInventory(projectRoot) {
  const manifest = readManifest(projectRoot);
  if (!manifest) return { installed: false, manifest: null };
  return {
    installed: true,
    manifestPath: relativeToProject(projectRoot, manifestPath(projectRoot)),
    hosts: manifest.hosts,
    files: manifest.files.map((record) => {
      const target = managedPath(projectRoot, record.path, "INSTALL_MANIFEST_PATH_INVALID").absolute;
      const exists = existsSync(target) && lstatSync(target).isFile();
      const currentSha256 = exists ? fileHash(target) : null;
      return {
        path: record.path,
        hosts: record.hosts,
        managed: record.managed,
        state: !exists ? "missing" : currentSha256 === record.installedSha256 ? "current" : "modified",
        installedSha256: record.installedSha256,
        currentSha256,
        backupPath: record.backupPath
      };
    })
  };
}
